# Generated by Django 5.0.7 on 2024-07-22 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_document_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Document',
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
