# Generated by Django 5.0.7 on 2024-07-31 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_page_created_at_page_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='slug',
        ),
        migrations.AddField(
            model_name='page',
            name='type',
            field=models.CharField(default=(('content', 'previous_migration_file'),), max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='page',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
