# Generated by Django 5.0.7 on 2024-07-31 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_remove_page_slug_page_type_alter_page_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='page',
            name='type',
        ),
        migrations.RemoveField(
            model_name='page',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='page',
            name='slug',
            field=models.SlugField(default=0, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='page',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
